language: objective-c
osx_image: xcode9.2
before_install:
- sudo gem install cocoapods
- pod repo update
- sudo gem install xcpretty
- carthage version
script: travis_wait 30 set -o pipefail && make build
