language: objective-c
osx_image: xcode9.3
before_install:
- sudo gem install cocoapods
- pod repo update
- sudo gem install xcpretty
- cd SanityTest; pod install
- make git-clone
script: travis_wait 30 set -o pipefail && make clean build
