# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SanityTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SanityTest
  pod 'Kinvey', :git => 'https://github.com/Kinvey/swift-sdk.git', :branch => 'develop'

  target 'SanityTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SanityTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
